FROM docker.productsup.com/cde/cde-php-cli-dev:8.3


RUN apt-get update && apt-get install -y jq
RUN apt-get install -y wget unzip

RUN wget https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip \
    && unzip duckdb_cli-linux-amd64.zip -d /usr/local/bin \
    && rm duckdb_cli-linux-amd64.zip
RUN duckdb -s "INSTALL json;LOAD json;"

